---

# Alpine linux kernel parameters configuration

- name: Test connection with user {{ ansible_user }} on port {{ ansible_port }}
  ping:

- name: Set net forwarding kernel params
  copy:
    dest: /etc/sysctl.d/forwarding.conf
    content: |
      net.ipv4.ip_forward = 1
      net.ipv6.conf.all.forwarding = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1

- name: Apply kernel parameter changes
  command: /sbin/sysctl -p /etc/sysctl.d/forwarding.conf

- name: Set needed kernel modules in /etc/modules-load.d/k3s.conf
  copy:
    dest: /etc/modules-load.d/k3s.conf
    content: |
      br_netfilter
      iptable_nat
      iptable_filter
      ip6table_nat
      ip6table_filter
      nf_conntrack
      overlay

- name: Install apk packages linux-virt linux-virt-dev iptables
  community.general.apk:
    name: linux-virt,linux-virt-dev
    update_cache: true
    state: present
  register: apk_add_linux_virt_iptables
  until: apk_add_linux_virt_iptables is succeeded
  retries: "{{ apk_retry_count }}"
  delay: 5
  
- name: Modprobe br_netfilter
  command: /sbin/modprobe br_netfilter

- name: Set rc_cgroup_mode to unified
  lineinfile:
    path: /etc/rc.conf
    regexp: '^#rc_cgroup_mode='
    line: 'rc_cgroup_mode="unified"'

- name: Set default_kernel_opts for cgroup v2
  lineinfile:
    path: /etc/update-extlinux.conf
    regexp: '^default_kernel_opts='
    line: 'default_kernel_opts="quiet rootfstype=ext4 cgroup_no_v1=all systemd.unified_cgroup_hierarchy=1 reboot=hard"'

#- name: Correct /sbin/extlinux reference in /sbin/update-extlinux
#  ansible.builtin.lineinfile:
#    path: /sbin/update-extlinux
#    search_string: 'ext*) extlinux --update /boot || [ -n "$warn_only" ];;'
#    line: 'ext*) /sbin/extlinux --update /boot || [ -n "$warn_only" ];;'

- name: Run update-extlinux to regenerate /boot/extlinux.conf
  command: /sbin/update-extlinux

- name: Enable service cgroups, and not touch the state
  ansible.builtin.service:
    name: cgroups
    runlevel: default
    enabled: yes

- name: Reboot to apply cgroup v2 settings and kernel parameter changes
  reboot:
    msg: "Rebooting to enable cgroups v2"
    connect_timeout: 10
    reboot_timeout: 300
    test_command: whoami

- name: Test connection with user {{ ansible_user }} on port {{ ansible_port }}
  ping:

- name: Verify cgroups v2 is mounted
  command: stat -fc %T /sys/fs/cgroup
  register: cgroupfs_type
  changed_when: false

- name: Fail if cgroup v2 is not active
  fail:
    msg: "ERROR: cgroup v2 is not active on /sys/fs/cgroup"
  when: '"cgroup2fs" not in cgroupfs_type.stdout and "UNKNOWN" not in cgroupfs_type.stdout'

- name: Confirm cgroup.controllers exists
  stat:
    path: /sys/fs/cgroup/cgroup.controllers
  register: cgctl

- name: Fail if cgroup.controllers is missing (not cgroup v2)
  fail:
    msg: "ERROR: cgroup.controllers file is missing â€” cgroup v2 not mounted properly"
  when: not cgctl.stat.exists
